// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1884.Robot.subsystems;

import org.usfirst.frc1884.Robot.RobotMap;
import org.usfirst.frc1884.Robot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class Shooter extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder shooterEncoder = RobotMap.shooterShooterEncoder;
    SpeedController shooterMotor = RobotMap.shooterShooterMotor;
    Solenoid ballReleasePiston = RobotMap.shooterBallReleasePiston;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static final double NEUTRAL = 101;
    public static final double FIRE = 102;
    public static final double POST_FIRE = 103;
    public static final long PISTON_RAISE_TIME = 150;
    private PistonClass pistonClass;

    // Initialize your subsystem here
    public Shooter() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("Shooter", 1.0, 0.0, 0.0);
        setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(true);
        LiveWindow.addActuator("Shooter", "PIDSubsystem Controller", getPIDController());
        getPIDController().setOutputRange(-1.0, 1.0);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        pistonClass = new PistonClass();
        enable();
        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }

    /**
     * This raises and lowers the piston.
     */
    public void pumpPistion() {
        pistonClass.runThread();
    }

    private class PistonClass implements Runnable {

        private boolean isRunning;
        private Thread thisThread;
        
        private PistonClass() {
            isRunning = false;
            thisThread = new Thread(this);
        }

        void runThread() {
            if (!isRunning) {
                thisThread.run();
            }
        }

        public void run() {
            isRunning = true;
            ballReleasePiston.set(true);
            try {
                Thread.sleep(PISTON_RAISE_TIME);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
            ballReleasePiston.set(false);
            isRunning = false;
        }

    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return shooterEncoder.pidGet();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
        shooterMotor.pidWrite(output);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    }
}
